Merged PR 654: chore(deps): update Prettier
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [prettier](https://prettier.io) ([source](https://github.com/prettier/prettier)) | devDependencies | minor | [`^3.3.2` -> `^3.6.2`](https://renovatebot.com/diffs/npm/prettier/3.3.2/3.6.2) |
| [pretty-quick](https://github.com/prettier/pretty-quick) | devDependencies | minor | [`^4.0.0` -> `^4.2.2`](https://renovatebot.com/diffs/npm/pretty-quick/4.0.0/4.2.2) |

---

### Release Notes

<details>
<summary>prettier/prettier (prettier)</summary>

### [`v3.6.2`](https://github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#362)

[Compare Source](https://github.com/prettier/prettier/compare/3.6.1...3.6.2)

[diff](https://github.com/prettier/prettier/compare/3.6.1...3.6.2)

##### Markdown: Add missing blank line around code block ([#&#8203;17675](https://github.com/prettier/prettier/pull/17675) by [@&#8203;fisker](https://github.com/fisker))

<!-- prettier-ignore -->

````md
<!-- Input -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List

<!-- Prettier 3.6.1 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```
   1. Another
   2. List

<!-- Prettier 3.6.2 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List
````

### [`v3.6.1`](https://github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#361)

[Compare Source](https://github.com/prettier/prettier/compare/3.6.0...3.6.1)

[diff](https://github.com/prettier/prettier/compare/3.6.0...3.6.1)

##### TypeScript: Allow const without initializer ([#&#8203;17650](https://github.com/prettier/prettier/pull/17650), [#&#8203;17654](https://github.com/prettier/prettier/pull/17654) by [@&#8203;fisker](https://github.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
export const version: string;

// Prettier 3.6.0 (--parser=babel-ts)
SyntaxError: Unexpected token (1:21)
> 1 | export const version: string;
    |                     ^

// Prettier 3.6.0 (--parser=oxc-ts)
SyntaxError: Missing initializer in const declaration (1:14)
> 1 | export const version: string;
    |              ^^^^^^^^^^^^^^^

// Prettier 3.6.1
export const version: string;
```

##### Miscellaneous: Avoid closing files multiple times ([#&#8203;17665](https://github.com/prettier/prettier/pull/17665) by [@&#8203;43081j](https://github.com/43081j))

When reading a file to infer the interpreter from a shebang, we use the
`n-readlines` library to read the first line in order to get the shebang.

This library closes files when it reaches EOF, and we later try close the same
files again. We now close files only if `n-readlines` did not already close
them.

### [`v3.6.0`](https://github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#360)

[Compare Source](https://github.com/prettier/prettier/compare/3.5.3...3.6.0)

[diff](https://github.com/pretti...